### PR TITLE
--username option

### PR DESCRIPTION
**Pull request by yuya-takeyama**
Some people has different username

### CODE REVIEW

**Comment by yuya-takeyama** [comment]
Oops.
I'll resolve this conflict and re-push.
conflict

**Comment by yuya-takeyama** [comment]
Resolved conflict and `git push -f`'d it.

**Comment by tcnksm** [comment]
Thanks, I'll fix a little and merge later :+1:

**Comment by tcnksm** [comment]
Hi, sorry for late, but I rewrote `cli-init` from scratch and support this option (to change owner name).  Try it on new version, 

```bash
$ cd $GOPATH/src/github.com/YOUR_NAME
$ cli-init new -owner YOUR_NAME -c add todo 
```

**Comment by yuya-takeyama** [comment]
Thanks!
I'll try it.

**Pull request closed without merging**
